ERROR - 2024-11-06 19:58:09 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=17728 in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 186)
#1 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'login', 3306, '', 0)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'login', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-11-06 19:58:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
[Method: POST, Route: login/authenticate]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 19:58:13 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'login', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-11-06 19:58:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: POST, Route: login/authenticate]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 19:58:19 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'login', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-11-06 19:58:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
[Method: POST, Route: login/authenticate]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Admin.php(23): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->authenticate()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 20:37:39 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'login' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'login', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1485): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1505): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\ci4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\ci4\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'login' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1485): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1505): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\ci4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\ci4\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-11-06 21:05:09 --> ErrorException: Undefined array key "avaliado"
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 136.
 1 APPPATH\Views\avaliador\dashboard.php(136): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "avaliado"', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 136)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:05:16 --> ErrorException: Undefined array key "avaliado"
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 136.
 1 APPPATH\Views\avaliador\dashboard.php(136): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "avaliado"', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 136)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:06:47 --> ErrorException: Undefined array key "avaliado"
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 136.
 1 APPPATH\Views\avaliador\dashboard.php(136): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "avaliado"', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 136)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:07:00 --> ErrorException: Undefined array key "avaliado"
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 136.
 1 APPPATH\Views\avaliador\dashboard.php(136): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "avaliado"', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 136)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:07:03 --> ErrorException: Undefined array key "avaliado"
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 136.
 1 APPPATH\Views\avaliador\dashboard.php(136): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "avaliado"', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 136)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:11:43 --> ErrorException: Undefined variable $notas
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 131.
 1 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $notas', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 131)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:14:13 --> mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(131): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-11-06 21:14:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
[Method: POST, Route: trabalho/avaliarOral]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:13 --> [Caused by] mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:14:48 --> mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(131): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-11-06 21:14:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
[Method: POST, Route: trabalho/avaliarOral]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:48 --> [Caused by] mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:14:51 --> mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(131): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-11-06 21:14:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
[Method: POST, Route: trabalho/avaliarOral]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:14:51 --> [Caused by] mysqli_sql_exception: Column 'habilidade_organizacao_logica' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (\'1\', \'4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes_orais` (`trabalho_id`, `introducao_clareza_objetividade`, `habilidade_organizacao_logica`, `repeticoes_digressoes`, `clareza_minuciosidade`, `conclusao_objetiva`, `independencia_raciocinio`, `tempo_satisfatorio`, `comentario`) VALUES (:trabalho_id:, :introducao_clareza_objetividade:, :habilidade_organizacao_logica:, :repeticoes_digressoes:, :clareza_minuciosidade:, :conclusao_objetiva:, :independencia_raciocinio:, :tempo_satisfatorio:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Avaliador.php(131): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:15:45 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#11 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-06 21:15:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
[Method: POST, Route: trabalho/avaliar]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:15:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:15:45 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:16:11 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#11 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-06 21:16:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
[Method: POST, Route: trabalho/avaliar]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:16:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:16:11 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'10\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'10\', 9.4, \'Boa noite!\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:32:49 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:34:37 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:35:44 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:36:35 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:36:38 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:37:33 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:39:00 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:40:26 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:40:36 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:41:34 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:41:42 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-06 21:43:12 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `av...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `av...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `av...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `av...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4\app\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
#10 C:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
#11 C:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-06 21:43:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
[Method: POST, Route: trabalho/avaliar]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:43:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', 9.1, \'Boa noite\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', 9.1, \'Boa noite\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:43:12 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`login`.`avaliacoes`, CONSTRAINT `avaliacoes_ibfk_1` FOREIGN KEY (`trabalho_id`) REFERENCES `trabalhos` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', 9.1, \'Boa noite\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', 9.1, \'Boa noite\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (\'\', \'10\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', \'9\', 9.1, \'Boa noite\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `avaliacoes` (`trabalho_id`, `elementosPainel`, `clarezaInformacoes`, `autoresDescritores`, `distribuicaoInformacoes`, `apresentacao`, `pensamentoCientifico`, `habilidade`, `clareza`, `minuciosidade`, `conclusao`, `media`, `comentario`) VALUES (:trabalho_id:, :elementosPainel:, :clarezaInformacoes:, :autoresDescritores:, :distribuicaoInformacoes:, :apresentacao:, :pensamentoCientifico:, :habilidade:, :clareza:, :minuciosidade:, :conclusao:, :media:, :comentario:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Avaliador.php(79): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliar()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 21:46:00 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:45:03 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:45:07 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:45:21 --> ErrorException: Undefined array key "independencia_raciocionio"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 130.
 1 APPPATH\Controllers\Avaliador.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "independencia_raciocionio"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 130)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:47:50 --> ErrorException: Undefined array key "repeticoes_digressoes"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 128.
 1 APPPATH\Controllers\Avaliador.php(128): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "repeticoes_digressoes"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 128)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:48:47 --> ErrorException: Undefined array key "repeticoes_digressoes"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 128.
 1 APPPATH\Controllers\Avaliador.php(128): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "repeticoes_digressoes"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 128)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:49:32 --> ErrorException: Undefined array key "repeticoes_digressoes"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 128.
 1 APPPATH\Controllers\Avaliador.php(128): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "repeticoes_digressoes"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 128)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:51:37 --> ErrorException: Undefined array key "repeticoes_digressoes"
[Method: POST, Route: trabalho/avaliarOral]
in APPPATH\Controllers\Avaliador.php on line 128.
 1 APPPATH\Controllers\Avaliador.php(128): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "repeticoes_digressoes"', 'C:\\xampp\\htdocs\\ci4\\app\\Controllers\\Avaliador.php', 128)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->avaliarOral()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:56:27 --> ErrorException: Undefined variable $filtro
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 138.
 1 APPPATH\Views\avaliador\dashboard.php(138): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $filtro', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 138)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:58:42 --> ErrorException: Undefined variable $filtro
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 139.
 1 APPPATH\Views\avaliador\dashboard.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $filtro', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 139)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-06 23:59:41 --> ErrorException: Undefined variable $filtro
[Method: GET, Route: avaliador/dashboard]
in APPPATH\Views\avaliador\dashboard.php on line 140.
 1 APPPATH\Views\avaliador\dashboard.php(140): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $filtro', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php', 140)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\avaliador\\dashboard.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('avaliador/dashboard', [], true)
 5 APPPATH\Controllers\Avaliador.php(17): view('avaliador/dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Avaliador->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Avaliador))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
